name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      # Keep running other jobs even if one fails
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
        dependencies:
          - 'oldest'
          - 'latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install oldest dependencies
        if: matrix.dependencies == 'oldest'
        run: |
          pip install -e . "jax==0.4.27" "jaxlib==0.4.27" "optax==0.2.4" "numpy==1.24.1"

      - name: Install latest dependencies
        if: matrix.dependencies == 'latest'
        run: |
          pip install -e . jax jaxlib optax numpy

      - name: Display installed versions
        # Useful for debugging which versions actually got installed
        run: pip freeze

      - name: Run tests
        run: pytest